### ISSUE TITLE
Missing tracking options

### ISSUE THREAD

**Issue by karls** [markhibberd/postmark#4]
Hi Mark!

I noticed that this library is missing the `TrackLinks` and `TrackOpens` options in the `Email` data type. Would you be interested in a pull request if I added them?

Thanks!

**Comment by novemberkilo** [comment]
Hi @karls, 

Adding support for tracking options would be terrific! Looking forward to your PR and please be in touch if there is anything we can do to assist ...

Thanks.

cc/ @markhibberd

**Comment by markhibberd** [comment]
This is in [v0.2.2](http://hackage.haskell.org/package/postmark-0.2.2).
